### ISSUE TITLE
Automatic-Module-Name in JAR's Manifest-File

### ISSUE THREAD

**Issue by metacodez** [dfish3r/vt-crypt#1]
Dear `vt-crypt` developers, your middleware eases the use of cryptography enormously! Thank you very much for your effort! I wonder if there are plans to support Java 9 modules so other projects could provide `vt-crypt` in their `module-info.java` declarations.

I think it would be sufficient to put an entry into `vt-crypt`'s JAR Manifest-File, such as: `Automatic-Module-Name: edu.vt.middleware.vt-crypt` to get stable module references. In Maven, this can be achieved by tweaking the maven-jar-plugin similar to:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			...
			<manifestEntries>
				<Automatic-Module-Name>edu.vt.middleware.vt-crypt</Automatic-Module-Name>
			</manifestEntries>
		</archive>
	</configuration>
	...
</plugin>
```

Or is `vt-crypt` end-of-development or did `vt-crypt` move to another repository / maven group?

Thanks beforehand and best regards!

**Comment by dfish3r** [comment]
vt-crypt has been replaced by cryptacular: https://github.com/vt-middleware/cryptacular

This project is no longer maintained.
